apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueforge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueforge-api
  template:
    metadata:
      labels:
        app: queueforge-api
    spec:
      containers:
        - name: api
          image: queueforge-api:local
          imagePullPolicy: IfNotPresent
          command:
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: DATABASE_URL

            - name: TEST_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: TEST_DATABASE_URL

            - name: REDIS_URL
              value: redis://redis:6379/0
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: queueforge-api
spec:
  type: NodePort
  selector:
    app: queueforge-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
