apiVersion: batch/v1
kind: Job
metadata:
  name: queueforge-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: queueforge-api:local
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - upgrade
            - head
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: DATABASE_URL

            - name: TEST_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: TEST_DATABASE_URL

            - name: REDIS_URL
              value: redis://redis:6379/0

  backoffLimit: 3
