apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueforge-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queueforge-worker
  template:
    metadata:
      labels:
        app: queueforge-worker
    spec:
      containers:
        - name: worker
          image: queueforge-api:local
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - app.celery_app.celery_app
            - worker
            - --loglevel=info
            - --concurrency=2
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: DATABASE_URL

            - name: TEST_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: queueforge-secrets
                  key: TEST_DATABASE_URL

            - name: REDIS_URL
              value: redis://redis:6379/0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
