apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueforge-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueforge-worker
  template:
    metadata:
      labels:
        app: queueforge-worker
    spec:
      containers:
        - name: worker
          image: queueforge-api:local
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - app.celery_app.celery_app
            - worker
            - --loglevel=info
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://postgres:queueforge@postgres:5432/queueforge
            - name: TEST_DATABASE_URL
              value: postgresql+psycopg://postgres:queueforge@postgres:5432/queueforge_test
            - name: REDIS_URL
              value: redis://redis:6379/0
