{
 "title": "QueueForge Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Upload Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queueforge_job_upload_size_bytes_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queueforge_jobs_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Dispatched",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queueforge_job_dispatch_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job Creation Rate",
   "type": "timeseries",
   "description": "Jobs created per second over time.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(queueforge_jobs_created_total[1m])",
     "legendFormat": "Jobs/sec"
    }
   ]
  },
  {
   "title": "Average Upload Size",
   "type": "timeseries",
   "description": "Average uploaded CSV size per job over time.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "queueforge_job_upload_size_bytes_sum\r\n/\r\nqueueforge_job_upload_size_bytes_count",
     "legendFormat": "Average size"
    }
   ]
  }
 ]
}